### ISSUE TITLE
serverInfo stopped working between 5.5 and 5.6

### ISSUE THREAD

**Issue by haileyajohnson** [Unidata/thredds-docker#323]
Hey folks! I'm trying to deploy thredds-docker 5.8 (yay!) and but the serverInfo endpoint is 404ing. I tried the out-of-the-box image, and then backed up the release versions until it worked again, and it last worked in 5.5. I think it's an issue in the tomcat settings in the dockerfile, rather than in the TDS itself, since I see unidata's TDS has serverInfo working. JSP problem? I tried for a while to track it down but then figured I would just ask.

Thanks!

**Comment by haileyajohnson** [comment]
UGH nevermind I have figured it out - the default tomcat/conf/web.xml just needs the CORS filter. I will close this issue. Thanks!

**Comment by haileyajohnson** [comment]
Double nevermind, changing CORS fixed another problem but my serverInfo is still 404ing, sorry for the confusion! :(

**Comment by ana-v-espinoza** [comment]
Hi Hailey,

Good to hear from you. @lesserwhirls , any idea what the problem could be? Happy to work with both of you to figure this out.

ana

**Comment by julienchastang** [comment]
Hi Hailey!

In addition, do you see anything in the TDS or Tomcat logs that may be amiss?

**Comment by haileyajohnson** [comment]
There's some jakarta/javax confusion going on (see log error below), but I _think_ it is actually a problem in the base tomecat-10 image, it looks like they're still packaging the old javax libraries. So that's fun.

30-Oct-2025 20:26:55.320 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [/thredds] threw exception [java.lang.NoClassDefFoundError: javax/servlet/jsp/tagext/TagLibraryValidator] with root cause java.lang.ClassNotFoundException: javax.servlet.jsp.tagext.TagLibraryValidator at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1377) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186) at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2359) at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2224) at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1338) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186) at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2359) at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2224) at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1338) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186) at org.apache.jasper.compiler.TagLibraryInfoImpl.createValidator(TagLibraryInfoImpl.java:346) at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:186) at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:405) at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:458) at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1351) at org.apache.jasper.compiler.Parser.parse(Parser.java:127) at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:240) at org.apache.jasper.compiler.ParserController.parse(ParserController.java:103) at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:188) at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361) at org.apache.jasper.compiler.Compiler.compile(Compiler.java:339) at org.apache.jasper.compiler.Compiler.compile(Compiler.java:325) at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:586) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:368) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:350) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:301) at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)

**Comment by haileyajohnson** [comment]
I was able to fix it by adding this to my dockerfile:

~~~
RUN rm -f taglibs-standard-impl-*.jar taglibs-standard-spec-*.jar
ADD https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0/jakarta.servlet.jsp.jstl-api-2.0.0.jar ./
ADD https://repo1.maven.org/maven2/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar ./
~~~

**Comment by julienchastang** [comment]
I think that sounds about right. serverInfo.jsp is not looked at too often evidently so we did not notice it until now. Thanks for pointing this out. We will create a PR to address this in the near future.

**Comment by julienchastang** [comment]
Hello to you both. Unless I’m missing something, this does not appear to be a `thredds-docker` issue but rather a problem in the TDS 5.6+ WAR itself. The `thredds-5.8.war` bundles both the correct Jakarta JSTL 2.0.0 libraries and the legacy Javax-based Standard Taglibs:

```bash
➜  /tmp curl -fsSL https://downloads.unidata.ucar.edu/tds/5.8/thredds-5.8.war -o /tmp/tds.war unzip -l /tmp/tds.war | egrep 'taglibs|jstl'

  3704112  08-13-2025 10:02   WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar
    46024  08-13-2025 10:02   WEB-INF/lib/jakarta.servlet.jsp.jstl-api-2.0.0.jar
    40153  08-13-2025 10:02   WEB-INF/lib/taglibs-standard-spec-1.2.5.jar
   206430  08-13-2025 10:02   WEB-INF/lib/taglibs-standard-impl-1.2.5.jar
```

According to the [5.6 release notes](https://github.com/Unidata/tds/releases/tag/v5.6), Tomcat 10 has been required since that version. The Javax-era Standard Taglibs are incompatible with Tomcat 10. Removing those from the TDS WAR build should resolve the issue.

**Comment by FObersteiner** [comment]
FYI, serverInfo doesn't work for me either (<https://thredds.atmohub.kit.edu/thredds/serverInfo.html>) - this is a docker deployment of 5.8.

**Comment by haileyajohnson** [comment]
@julienchastang yes you're correct, the javax libraries need to be cleaned out of the thredds war itself.

@FObersteiner if you want a workaround, you can wrap the thredds 5.8 dockerfile in your own that just has this:
```
FROM unidata/thredds-docker:5.8

WORKDIR /usr/local/tomcat/webapps/thredds/WEB-INF/lib

RUN rm -f taglibs-standard-impl-*.jar taglibs-standard-spec-*.jar
```

**Comment by lesserwhirls** [comment]
I'll get the TDS updated to remove the old taglibs dependencies. There is quite a bit of cleanup that needs to happen with the JSPs as well (several old JSPs referencing  http://java.sun.com/jsp/jstl/core that are no longer used, for example). What I don't quite understand yet is why not all TDSs are impacted. For example, https://tds.scigw.unidata.ucar.edu/thredds/info/serverInfo.html does not 404, and neither does https://thredds.ucar.edu/thredds/info/serverInfo.html

**Comment by lesserwhirls** [comment]
This should be addressed in the latest `5.9-SNAPSHOT` image.
